language: c++
language: python
python:
  - "3.7"

sudo: on

before_install:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq

install:
  - ./interpreter/meta/travis/install-ocaml.sh
  - sudo pip install Sphinx==2.3.0
  - sudo apt-get install texlive-full yarn
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update

script:
  - ./interpreter/meta/travis/build-test.sh
  - bash ./document/travis-deploy.sh

os: linux

env:
  global:
    - ENCRYPTION_LABEL: "304454be9d6c"
    - COMMIT_AUTHOR_EMAIL: "noreply@webassembly.org"
