language: c++
language: python
python:
  - "3.7"
dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - ocaml
      - ocamlbuild
      - texlive-full
      - yarn

install:
  - pip install Sphinx==2.3.0
  - sudo apt-get install texlive-full yarn
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update

script:
  - ./interpreter/meta/travis/build-test.sh
  - bash ./document/travis-deploy.sh

os: linux

env:
  global:
    - ENCRYPTION_LABEL: "304454be9d6c"
    - COMMIT_AUTHOR_EMAIL: "noreply@webassembly.org"
