language: python
python:
  - "3.7"
dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'ppa:avsm/ppa'
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    update: true
    packages:
      - opam
      - texlive-full
      - yarn

install:
  - opam init --auto-setup --compiler=4.07.1
  - eval $(opam env)
  - opam --version
  - ocaml --version
  - opam install --yes ocamlbuild.0.14.0
  - pip install Sphinx==2.4.4
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update

script:
  - ./interpreter/meta/travis/build-test.sh
  - bash ./document/travis-deploy.sh

os: linux

env:
  global:
    - ENCRYPTION_LABEL: "5d9ec396f41d"
    - COMMIT_AUTHOR_EMAIL: "noreply@webassembly.org"
