language: c++
language: python
python:
  - "2.7"

sudo: on

install:
  - ./interpreter/meta/travis/install-ocaml.sh
  - sudo pip install sphinx==1.7.9
  - sudo apt-get install texlive-full
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update

script:
  - ./interpreter/meta/travis/build-test.sh
  - bash ./document/travis-deploy.sh

os: linux

env:
  global:
    - ENCRYPTION_LABEL: "304454be9d6c"
    - COMMIT_AUTHOR_EMAIL: "noreply@webassembly.org"
