name: CI for interpreter & tests

on:
  push:
    branches: [ main ]
    paths: [ .github/**, interpreter/**, test/** ]

  pull_request:
    branches: [ main ]
    paths: [ .github/**, interpreter/**, test/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  interpreter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x
      - name: Setup OCaml tools
        run: opam install --yes ocamlfind.1.9.5 js_of_ocaml.4.0.0 js_of_ocaml-ppx.4.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Build interpreter
        run: cd interpreter && opam exec make
      - name: Run tests
        # TODO: reactiate node once it supports all of Wasm 3.0
        # run: cd interpreter && opam exec make JS=node ci
        run: cd interpreter && opam exec make ci
